# Generated by Django 4.2.5 on 2023-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_producttype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
