# Generated by Django 4.2.5 on 2023-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_remove_producttype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Change product visibility",
                verbose_name="Product visibility",
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Change product type visibility",
                verbose_name="Product type visibility",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                help_text="Required and unique",
                max_length=255,
                unique=True,
                verbose_name="Category name",
            ),
        ),
    ]
