# Generated by Django 4.2.5 on 2023-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_product_is_active_producttype_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Change product visibility",
                verbose_name="Product is visible",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Change product type visibility",
                verbose_name="Product type is visible",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(blank=True, to="store.color"),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="store.size"),
        ),
    ]
