# Generated by Django 4.2.5 on 2023-09-24 23:20

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_color_size_remove_product_color_remove_product_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to=store.models.product_image_file_path,
            ),
        ),
    ]
