# Generated by Django 4.2.5 on 2024-02-10 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_remove_product_image_productimage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="product_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="store.producttype",
            ),
            preserve_default=False,
        ),
    ]
