# Generated by Django 4.2.5 on 2024-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_remove_size_product_type_producttype_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
