# Generated by Django 4.2.5 on 2024-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_producttype_slug_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
