# Generated by Django 4.2.5 on 2024-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_alter_product_slug_alter_producttype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
