# Generated by Django 4.2.5 on 2024-02-11 23:03

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_alter_producttype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.product_image_file_path
            ),
        ),
    ]
